Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
"""List: A list in Python is a collection of items which can contain elements of multiple data types, which may be either numeric, character logical values, etc. It is an ordered collection supporting negative indexing. A list can be created using [] containing data values. Contents of lists can be easily merged and copied using python’s inbuilt functions.
Array: An array is a vector containing homogeneous elements i.e. belonging to the same data type. Elements are allocated with contiguous memory locations. Typically the size of an array is fixed. Insertion and Deletion costs high as compare to List however indexing is fast in the Arrays due to contiguous memory allocation.

Operations Difference in Lists and Arrays : –
Arrays :- Accessing element is Fast in an array because they are in contiguous manner but insertion and deletion is quite expensive because all the elements are shifted from the position of inserting and deleting element linearly.

Suppose the array is of 1000 length and we are inserting/deleting element at 100 position then all the element after hundred position will get shifted due to which the operation become expensive.

Lists : – Accessing element in a list takes linear time because all the element in the lists are linked with each other for accessing ith element we have to traverse all the previous elements in a list however insertion and deletion in a list takes constant(which is not expensive at all) time as all the element are linked with each other for adding or removing new element we just remove the linked between the element and link new element like plumbing the pipe there is no need to shift element as in arrays.

Numpy arrays is a typed array, the array in memory stores a homogenous, densely packed numbers. Python list is a heterogeneous list, the list in memory stores references to objects rather than the number themselves. This means that Python list requires dereferencing a pointer every time the code needs to access the number."""

'List: A list in Python is a collection of items which can contain elements of multiple data types, which may be either numeric, character logical values, etc. It is an ordered collection supporting negative indexing. A list can be created using [] containing data values. Contents of lists can be easily merged and copied using python’s inbuilt functions.\nArray: An array is a vector containing homogeneous elements i.e. belonging to the same data type. Elements are allocated with contiguous memory locations. Typically the size of an array is fixed. Insertion and Deletion costs high as compare to List however indexing is fast in the Arrays due to contiguous memory allocation.\n\nOperations Difference in Lists and Arrays : –\nArrays :- Accessing element is Fast in an array because they are in contiguous manner but insertion and deletion is quite expensive because all the elements are shifted from the position of inserting and deleting element linearly.\n\nSuppose the array is of 1000 leng

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [6]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

# data type of each and every element of list_
for i in list_:
    t=type(i)
    print("type","(",i,")","=",t)

type ( 1 ) = <class 'str'>
type ( 2 ) = <class 'str'>
type ( 3 ) = <class 'str'>
type ( 4 ) = <class 'str'>
type ( 5 ) = <class 'str'>


In [7]:
#data type of each and every element of array_list
for i in np.nditer(array_list):
    l=[i]
    print (l)

[array('1', dtype='<U1')]
[array('2', dtype='<U1')]
[array('3', dtype='<U1')]
[array('4', dtype='<U1')]
[array('5', dtype='<U1')]


In [9]:
for i in array_list:
    l=i.dtype
    print ("type",'(',i,")",'=',l)

type ( 1 ) = <U1
type ( 2 ) = <U1
type ( 3 ) = <U1
type ( 4 ) = <U1
type ( 5 ) = <U1


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [10]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_, dtype = int)

# data type of each and every element of list_
for i in list_:
    t=type(i)
    print("type","(",i,")","=",t)

type ( 1 ) = <class 'str'>
type ( 2 ) = <class 'str'>
type ( 3 ) = <class 'str'>
type ( 4 ) = <class 'str'>
type ( 5 ) = <class 'str'>


In [11]:
for i in array_list:
    l=i.dtype
    print (l)

int64
int64
int64
int64
int64


In [12]:
#yes there is a change in datatypes of elements in array_list ,all the data which was earlier of type "<U1" changed to int64,while there is no change in data type of list_ elements 

Q4.Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [13]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#code to get size
num_array_size=np.size(num_array)
#code to get shape
num_array_shape=np.shape(num_array)

print("num_array_size","=",num_array_size)
print("num_array_shape",'=',num_array_shape)

num_array_size = 6
num_array_shape = (2, 3)


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [17]:
zero_matrix_array=np.zeros((3,3))
print('zero_matrix_array','=>')
print(zero_matrix_array)
print("size","=",np.size(zero_matrix_array))
print('shape',"=",np.shape(zero_matrix_array))

zero_matrix_array =>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
size = 9
shape = (3, 3)


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [15]:
import numpy.matlib as nm
iden_mat=nm.eye(5)
iden_mat

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])